export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import SideBar from "../_components/sidebar";
import "../_styles/globals.css";
import Link from "next/link";
import UserEmail from "./email";
import { signOutAction } from "../actions";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className=" grid grid-cols-6 min-h-screen">
          <div className=" col-span-2 lg:col-span-1 flex flex-col  bg-[var(--secondary-color)] items-center">
            <SideBar />
            <div className=" flex-1 flex flex-col justify-end text-white p-8 w-full space-y-4">
              <div>
                <p>Free Tokens 40</p>
              </div>

              <div>
                <UserEmail />
              </div>

              <form action={signOutAction}>
                <button
                  type="submit"
                  className="w-full py-2 bg-white rounded text-center text-[var(--secondary-color)]"
                >
                  Logout
                </button>
              </form>
            </div>
          </div>
          <div className="col-span-4 lg:col-span-5 ">{children}</div>
        </main>
      </body>
    </html>
  );
}
