export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import SideBar from "../_components/sidebar";
import "../_styles/globals.css";
import UserEmail from "./email";
import { signOutAction } from "../actions";
import Provider from "@/utils/Providers";
import { ToastContainer, toast } from "react-toastify";
import FreeTokens from "./free_token";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <main className=" grid grid-cols-6 min-h-screen overflow-hidden">
          <div className=" col-span-2 lg:col-span-1 flex flex-col  bg-[var(--secondary-color)] items-center">
            <SideBar />
            <div className=" flex-1 flex flex-col justify-end text-white p-8 w-full space-y-4">
              <div>
                <FreeTokens />
              </div>

              <div>
                <UserEmail />
              </div>

              <form action={signOutAction}>
                <button
                  type="submit"
                  className="w-full py-2 bg-white rounded text-center text-[var(--secondary-color)]"
                >
                  Logout
                </button>
              </form>
            </div>
          </div>
          <div className="h-screen flex flex-col col-span-4 lg:col-span-5 ">
            <Provider> {children}</Provider>
          </div>
        </main>
      </body>
    </html>
  );
}
